name: CI
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: rm .github -r
      - run: (Get-Content 'sample.sh' -Raw) -match "\r\n$"